openapi: '3.1.0'
info:
  title: BOTB Plugin
  description: Access VMs, crypto, devices, logs, and zip files.
  version: "1.0.0"
servers:
  - url: https://botb-openai-plugin.onrender.com
paths:
  /crypto/{symbol}:
    get:
      operationId: get_crypto_price
      summary: Get crypto price
      parameters:
        - in: path
          name: symbol
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Crypto price
  /healthz:
    get:
      operationId: get_health_status
      summary: Health check
      responses:
        '200':
          description: OK
